//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.20 at 10:43:40 AM CEST 
//


package de.mfz.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}startzeitpunkt"/>
 *         &lt;element ref="{}startpunkt"/>
 *         &lt;element ref="{}zielpunkt"/>
 *         &lt;element ref="{}kfznamme"/>
 *         &lt;element ref="{}sitze"/>
 *         &lt;element ref="{}zwichenstopp" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "startzeitpunkt",
    "startpunkt",
    "zielpunkt",
    "kfznamme",
    "sitze",
    "zwichenstopp"
})
@XmlRootElement(name = "route")
public class Route {

    @XmlElement(required = true)
    protected String startzeitpunkt;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String startpunkt;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String zielpunkt;
    @XmlElement(required = true)
    protected String kfznamme;
    @XmlElement(required = true)
    protected BigInteger sitze;
    protected String zwichenstopp;

    /**
     * Gets the value of the startzeitpunkt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartzeitpunkt() {
        return startzeitpunkt;
    }

    /**
     * Sets the value of the startzeitpunkt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartzeitpunkt(String value) {
        this.startzeitpunkt = value;
    }

    /**
     * Gets the value of the startpunkt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartpunkt() {
        return startpunkt;
    }

    /**
     * Sets the value of the startpunkt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartpunkt(String value) {
        this.startpunkt = value;
    }

    /**
     * Gets the value of the zielpunkt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZielpunkt() {
        return zielpunkt;
    }

    /**
     * Sets the value of the zielpunkt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZielpunkt(String value) {
        this.zielpunkt = value;
    }

    /**
     * Gets the value of the kfznamme property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKfznamme() {
        return kfznamme;
    }

    /**
     * Sets the value of the kfznamme property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKfznamme(String value) {
        this.kfznamme = value;
    }

    /**
     * Gets the value of the sitze property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSitze() {
        return sitze;
    }

    /**
     * Sets the value of the sitze property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSitze(BigInteger value) {
        this.sitze = value;
    }

    /**
     * Gets the value of the zwichenstopp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZwichenstopp() {
        return zwichenstopp;
    }

    /**
     * Sets the value of the zwichenstopp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZwichenstopp(String value) {
        this.zwichenstopp = value;
    }

}
